#!/bin/sh
echo "NA-Online Tools require:"
echo "- MNE-CPP for FIFF"
echo "- Eigen Library"
echo ""
echo "The destination folder is:"
echo $HOME"/na-online_dependencies/"
echo ""
echo "To change it, you can modify:"
echo `pwd`"/PackBacker/jobs/na-online_dependencies.pb"
echo ""
echo "If your distribution does not contain the following packages,"
echo "you have to install them:"
echo "- Eigen v3.1.1 or later"
echo ""
python3 ./PackBacker/packbacker.py ./PackBacker/jobs/na-online_dependencies.pb